language: node_js
os:
  - windows
  - linux
node_js:
  - 11
  - 10
  - 8
  - 6
cache: npm
before_install: if [[ "$(npm -v)" != "6.6.0" ]] && [[ "${TRAVIS_OS_NAME}" != "windows" ]]; then npm install --global npm@6.6.0; fi
after_script:
- 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
